version: "3.8"

services:
  
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on: 
      - backend
      - app
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app:
    image: react_frontend
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
      - mysql
    ports:
      - 8080:80
    restart: unless-stopped

  backend:
    image: backend
    container_name: express_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    ports:
      - 5000:5000
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  mysql-data: