version: "3.8"

services:
  
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on: 
      - backend
      - app
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app:    
    image: react_frontend
    container_name: app
    stdin_open: true
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
        - 3000:3000

  # Start backend using nodemon
  backend:
    image: node:latest
    container_name: express_backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
    command: sh -c "yarn install && yarn dev"
    ports:
      - 5000:5000

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos      

volumes:
  mysql-data: