version: "3.8"

services:
  
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on: 
      - backend
      - app
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app:
    image: react_frontend
    container_name: app
    build: ./app
    depends_on:
      - backend
    ports:
        - 8080:80

  backend:
    image: node:latest
    container_name: express_backend
    command: sh -c "yarn install && node index"
    ports:
      - 3000:3000
    working_dir: /backend
    volumes:
      - ./backend:/backend

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos      

volumes:
  mysql-data: