name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Add .env file
      run: |
        touch .env
        echo MYSQL_HOST=${{ secrets.MYSQL_HOST }} >> .env
        echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .env
        echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env
        echo MYSQL_DB=${{ secrets.MYSQL_DB }} >> .env
        cat .env
    - name: Build the Docker image            
      run: docker-compose -f docker-compose.prod.yml up --force-recreate --build -d && docker image prune -f